// npm start
import React, { Component } from "react";

import { process_EMAIL_FROM, process_EMAIL_TO, process_API_KEY  } from './api_keys';


//Access to fetch at netlify app' from origin has been blocked by CORS policy
// react fetc error cors call netlify page
//what is correct way react fetch netlify page
//what is correct way react fetch netlify page error cors call
//what is correct way react fetch netlify api  to send email
// what is correct way call page with data on netlify
// fetch netlify page as api
// call netlify function from another domain


import "./App.css";

//npm install dotenv --save
// require('dotenv').config()


class App extends Component {
    constructor(props) {
    super(props);
    this.state = { apiResponse: "" };
  }

  callAPI() {
    console.log("=== callAPI start")
    // fetch("https://netlify-email.netlify.app"
    // const user_guid = "ggg321561";
    // const user_verify_token = "ttt4654321561";
    // const siteURL= "www.antinedoebit.com";
    // const tLink1 = `777 \\\\ //$ '+++' 7777`;

    const tSubject = "SignUp email verify letter";
    const tMessage = ` 
        <div style="margin: 20px auto;">
        
            <a>This e-mail Message is automaticaly generated by: www.xx.com </a>
    
        </div>`;
    const tSignature = ` 
        <div style="margin: 20px auto;">
        
            <a>This Signature </a>
    
        </div>`;
    const tFooter = ` 
        <div style="margin: 20px auto;">
        
            <a>This Footer </a>
    
        </div>`;

      var b = 'tttttttttttt';
      var sEncoded = b.toString('base64');
      console.log("=== sEncoded")
      console.log(sEncoded)

      b = sEncoded;
      var sDecoded = b.toString('base64');
      console.log("=== sDecoded")
      console.log(sDecoded)

      const tBody = {
          //npm install env-cmd
          "api_key": process_API_KEY,
          "email_from": process_EMAIL_FROM,
          "email_to":process_EMAIL_TO,
          "subject":tSubject,
          "message":tMessage,
          "signature":tSignature,
          "footer":tFooter,
      }

      console.log(`Environment ${process.env.API_KEY}`)
      console.log(tBody)

    fetch("https://netlify-email.netlify.app/.netlify/functions/send-email"


        ,{
            // body: "7777777 8888888",
            // body: tBody,
            body: JSON.stringify({
                "part1":tBody,
            }),
            mode: 'no-cors',
            method: 'POST',
            headers: {
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Headers": "Content-Type",
                "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTION",
            },
        }

        // , {
        //     mode: 'no-cors' // 'cors' by default
        // }
        )
    // fetch("http://localhost:9000/reset-password")
        .then(res => res.text())
        .then(res => {
            this.setState({apiResponse: res + " moment 2 "+Date.now()},
                (e) => {
                    console.log("=== callAPI OK")
                    console.log(res)
                    console.log(this.state.apiResponse)
                }
            )
        })
        .catch(err => {
            console.error("=== callAPI err")
            console.log(err)
        });
  }

  componentDidMount() {

  }

  render() {

      const onClick_sendAPI = (e) => {
          console.log("=== onClick_sendAPI(e)")

          this.callAPI();
      }

    return (
        <div className="App">
          <header className="App-header">
              <div
                  style={{width:'130px', height:'50px',
                      display:'flex',
                      flexDirection:'row',
                      justifyContent:'center',
                      backgroundColor:'red'}}>
                  <button  onClick={(e)=>onClick_sendAPI(e)}>SEND API</button>
              </div>          </header>
        </div>
    );
  }
}

export default App;
