// npm start
import React, { Component } from "react";

//npm i react-uuid
import uuid from 'react-uuid'

import {process_EMAIL_FROM, process_EMAIL_TO, process_API_KEY, process_API_URL} from './api_keys';

import "./App.css";
import SendEmail from "./SendEmail";


class App extends Component {
    constructor(props) {
    super(props);
        //  ================ email

        var email_data = {};

        email_data.tSubject = "!!! SignUp email verification letter --- "+ Date.now().toString()+"-";

        email_data.tMessage = ` 
        <div style="margin: 20px auto;">
        
            <a style="font-style: italic; font-weight: 600">This e-mail Message is automaticaly generated by: www.xx.com </a>
    
        </div>`;
        email_data.tSignature = ` 
        <div style="margin: 20px auto;">
                    
            <a>This is Signature </a>
            <div>           
            <img src="https://services.google.com/fh/files/emails/g1logo-01.png" width="50px" >
            </div>
    
        </div>`;

        email_data.tFooter = ` 
        <div style="margin: 20px auto;">
        
            <a>This is Footer </a>
    
        </div>`;

        //  ================ email end
        this.state = { apiResponse: "" , send_email:false, email_data:email_data};


    }

  callAPI() {
    console.log("=== callAPI start")


    const tSubject = "SignUp email verification letter --- "+ Date.now().toString()+"-"+uuid();
    const tMessage = ` 
        <div style="margin: 20px auto;">
        
            <a style="font-style: italic; font-weight: 600">This e-mail Message is automaticaly generated by: www.xx.com </a>
    
        </div>`;
    const tSignature = ` 
        <div style="margin: 20px auto;">
                    
            <a>This is Signature </a>
            <div>           
            <img src="https://services.google.com/fh/files/emails/g1logo-01.png" width="50px" >
            </div>
    
        </div>`;
    const tFooter = ` 
        <div style="margin: 20px auto;">
        
            <a>This is Footer </a>
    
        </div>`;



      var b = 'tttttttttttt';
      var sEncoded = b.toString('base64');
      console.log("=== sEncoded")
      console.log(sEncoded)

      b = sEncoded;
      var sDecoded = b.toString('base64');
      console.log("=== sDecoded")
      console.log(sDecoded)

      const tBody = {

          "api_key": process_API_KEY,
          "email_from": process_EMAIL_FROM,
          "email_to":process_EMAIL_TO,
          "subject":tSubject,
          "message":tMessage,
          "signature":tSignature,
          "footer":tFooter,
      }

      console.log(`Environment ${process.env.API_KEY}`)
      console.log(tBody)

    fetch("https://netlify-email.netlify.app/.netlify/functions/send-email"


        ,{
            // body: "7777777 8888888",
            // body: tBody,
            body: JSON.stringify({
                "part1":tBody,
            }),
            mode: 'no-cors',
            method: 'POST',
            headers: {
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Headers": "Content-Type",
                "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTION",
            },
        }

        // , {
        //     mode: 'no-cors' // 'cors' by default
        // }
        )
    // fetch("http://localhost:9000/reset-password")
        .then(res => res.text())
        .then(res => {
            this.setState({apiResponse: res + " moment 2 "+Date.now()},
                (e) => {
                    console.log("=== callAPI OK")
                    console.log(res)
                    console.log(this.state.apiResponse)
                }
            )
        })
        .catch(err => {
            console.error("=== callAPI err")
            console.log(err)
        });
  }

  componentDidMount() {

  }



  render() {

      const onClick_sendAPI = (e) => {
          console.log("=== onClick_sendAPI(e)")

          // this.callAPI();
          this.setState({send_email: true} )


      }

    return (
        <div className="App">
          <header className="App-header">
              <div
                  style={{width:'130px', height:'50px',
                      display:'flex',
                      flexDirection:'row',
                      justifyContent:'center',
                      backgroundColor:'red'}}>
                  <button  onClick={(e)=>onClick_sendAPI(e)}>SEND API</button>
              </div>
          </header>

            {(this.state.send_email)?
                <SendEmail
                    p_url ={process_API_URL}
                    p_api_key ={process_API_KEY}
                    p_email_from ={process_EMAIL_FROM}
                    p_email_to ={process_EMAIL_TO}

                    p_subject ={this.state.email_data.tSubject}
                    p_message ={this.state.email_data.tMessage}
                    p_signature ={this.state.email_data.tSignature}
                    p_footer ={this.state.email_data.tFooter}
                    p_call_back={()=>{
                        console.log('=== finish of SendEmail ')
                        this.setState({send_email: false} )
                    }}
                />
                :''
            }

        </div>
    );
  }
}

export default App;
